apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: auto-deploy-services
  namespace: argocd
spec:
  generators:
  - git:
      # URL này ĐÃ ĐÚNG (vì directories chạy được)
      repoURL: https://github.com/quypn23/argocd.git
      revision: HEAD
      files:
      # SỬA 1: Đường dẫn cụ thể đến file json
      # Dấu * thay cho tên folder (svc1, svc10...)
      - path: "gitOps-repo/values/*/config.json"

  template:
    metadata:
      # SỬA 2: Lấy tên từ file JSON (Không dùng path.basename nữa cho đỡ lỗi)
      name: '{{appName}}'
    spec:
      # SỬA 3: Lấy project từ file JSON
      project: '{{projectName}}'

      source:
        repoURL: https://github.com/quypn23/argocd.git
        targetRevision: HEAD
        path: gitOps-repo
        
        helm:
          valueFiles:
          # SỬA 4: Ghép đường dẫn dựa trên biến JSON
          # Đảm bảo appName trong JSON giống hệt tên thư mục (ví dụ: svc10)
          - 'values/{{appName}}/values.yaml'
          
      destination:
        server: https://kubernetes.default.svc
        # SỬA 5: Lấy namespace từ file JSON
        namespace: '{{destNamespace}}'
        
      syncPolicy:
        automated:
          prune: true
          selfHeal: true